#!/bin/bash -e
# shellcheck disable=SC2015

function main() {
  
  cd "$(dirname "$0")" || { err "unable to change directory"; return 2; }
  err "$(basename "$PWD")"
  err "  deleting"

  # shellcheck disable=SC2155
  export PATH="../bin/scripts:../bin/$(uname | tr '[:upper:]' '[:lower:]')/$(uname -m):$PATH"

  sanitycheck || { err "Failure deleting $(basename "$PWD"); see above"; return $?; }

  _main || { err "Failure deleting $(basename "$PWD"); see above"; return $?; }
  return 0
}

function _main() {

  local rc ns
  rc=0
  ns="$(basename "$PWD")"
  kubectl get ns "$ns" > /dev/null 2>&1 && {
    err "    - Kubernetes Namespace $ns"
    doit kubectl delete ns "$ns" || rc=3
  }

  id=$(apoctl api list namespaces -n "/$TENANT/$CLOUD/$GROUP" -f name=="/$TENANT/$CLOUD/$GROUP/$(basename "$PWD")" | jq -r '.[].ID')
  [[ "$id" ]] && {
    err "    -  Prisma Namespace $ns with id $id"
    doit apoctl api delete namespace  -n "/$TENANT/$CLOUD/$GROUP" "$id" || rc=3
  }

  err "done"
  return "$rc" 
}

function err() { echo "$@" 1>&2; }

main "$@"