#!/bin/bash

function main() {
  cd "$(dirname "$0")" || { err "unable to change directory"; return 2; }

  fail=false

  export NOBANNER="true"

  ../cloud/"$(basename "$0")" || { fail=true; }
  
  err ""
  ../group/"$(basename "$0")" || { fail=true; }

  err ""
  ../nashville/"$(basename "$0")" || { fail=true; }

  err ""
  ../memphis/"$(basename "$0")" || { fail=true; }

  err ""
  ../knoxville/"$(basename "$0")" || { fail=true; }

  "$fail" || {
    cat ../.banner >&2
    return 0
  }

  err "One or more failures"
  return 3
}

function err() { echo "$@" 1>&2; }

main "$@"