apiVersion: apps/v1
kind: Deployment
metadata:
  name: database1
  namespace: nashville
  labels:
    app: database
    sim-cloud: "AWS"
    sim-region: "us-east-1"
    sim-account: "10"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
      sim-cloud: "AWS"
      sim-region: "us-east-1"
      sim-account: "10"
  template:
    metadata:
      labels:
        app: database
        sim-cloud: "AWS"
        sim-region: "us-east-1"
        sim-account: "10"
        filter: demo
    spec:
      containers:
      - name: database
        image: jodydadescott/stupid-container
        command: ["/scripts/run"]
        ports:
        - containerPort: 80
        env:
        - name: LISTEN
          value: ":80"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_APP
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: wrapper
          mountPath: /scripts
      volumes:
      - name: wrapper
        configMap:
          name: run
          defaultMode: 0744
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database2
  namespace: nashville
  labels:
    app: database
    sim-cloud: "AWS"
    sim-region: "us-west-1"
    sim-account: "10"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
      sim-cloud: "AWS"
      sim-region: "us-west-1"
      sim-account: "10"
  template:
    metadata:
      labels:
        app: database
        sim-cloud: "AWS"
        sim-region: "us-west-1"
        sim-account: "10"
        filter: demo
    spec:
      containers:
      - name: database
        image: jodydadescott/stupid-container
        command: ["/scripts/run"]
        ports:
        - containerPort: 80
        env:
        - name: LISTEN
          value: ":80"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_APP
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: wrapper
          mountPath: /scripts
      volumes:
      - name: wrapper
        configMap:
          name: run
          defaultMode: 0744
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database3
  namespace: nashville
  labels:
    app: database
    sim-cloud: "AWS"
    sim-region: "us-east-1"
    sim-account: "20"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
      sim-cloud: "AWS"
      sim-region: "us-east-1"
      sim-account: "20"
  template:
    metadata:
      labels:
        app: database
        sim-cloud: "AWS"
        sim-region: "us-east-1"
        sim-account: "20"
        filter: demo
    spec:
      containers:
      - name: database
        image: jodydadescott/stupid-container
        command: ["/scripts/run"]
        ports:
        - containerPort: 80
        env:
        - name: LISTEN
          value: ":80"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_APP
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: wrapper
          mountPath: /scripts
      volumes:
      - name: wrapper
        configMap:
          name: run
          defaultMode: 0744
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database4
  namespace: nashville
  labels:
    app: database
    sim-cloud: "Azure"
    sim-region: "us-east-1"
    sim-account: "30"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
      sim-cloud: "Azure"
      sim-region: "us-east-1"
      sim-account: "30"
  template:
    metadata:
      labels:
        app: database
        sim-cloud: "Azure"
        sim-region: "us-east-1"
        sim-account: "30"
        filter: demo
    spec:
      containers:
      - name: database
        image: jodydadescott/stupid-container
        command: ["/scripts/run"]
        ports:
        - containerPort: 80
        env:
        - name: LISTEN
          value: ":80"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_APP
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: wrapper
          mountPath: /scripts
      volumes:
      - name: wrapper
        configMap:
          name: run
          defaultMode: 0744
