apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend1
  namespace: memphis
  labels:
    app: frontend
    sim-cloud: "AWS"
    sim-region: "us-east-1"
    sim-account: "10"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      sim-cloud: "AWS"
      sim-region: "us-east-1"
      sim-account: "10"
  template:
    metadata:
      labels:
        app: frontend
        sim-cloud: "AWS"
        sim-region: "us-east-1"
        sim-account: "10"
        filter: demo
    spec:
      containers:
      - name: frontend
        image: jodydadescott/stupid-container
        command: ["/scripts/run"]
        ports:
        - containerPort: 80
        env:
        - name: LISTEN
          value: ":80"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_APP
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: wrapper
          mountPath: /scripts
      volumes:
      - name: wrapper
        configMap:
          name: run
          defaultMode: 0744
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend2
  namespace: memphis
  labels:
    app: frontend
    sim-cloud: "AWS"
    sim-region: "us-west-1"
    sim-account: "10"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      sim-cloud: "AWS"
      sim-region: "us-west-1"
      sim-account: "10"
  template:
    metadata:
      labels:
        app: frontend
        sim-cloud: "AWS"
        sim-region: "us-west-1"
        sim-account: "10"
        filter: demo
    spec:
      containers:
      - name: frontend
        image: jodydadescott/stupid-container
        command: ["/scripts/run"]
        ports:
        - containerPort: 80
        env:
        - name: LISTEN
          value: ":80"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_APP
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: wrapper
          mountPath: /scripts
      volumes:
      - name: wrapper
        configMap:
          name: run
          defaultMode: 0744
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend3
  namespace: memphis
  labels:
    app: frontend
    sim-cloud: "AWS"
    sim-region: "us-east-1"
    sim-account: "20"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      sim-cloud: "AWS"
      sim-region: "us-east-1"
      sim-account: "20"
  template:
    metadata:
      labels:
        app: frontend
        sim-cloud: "AWS"
        sim-region: "us-east-1"
        sim-account: "20"
        filter: demo
    spec:
      containers:
      - name: frontend
        image: jodydadescott/stupid-container
        command: ["/scripts/run"]
        ports:
        - containerPort: 80
        env:
        - name: LISTEN
          value: ":80"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_APP
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: wrapper
          mountPath: /scripts
      volumes:
      - name: wrapper
        configMap:
          name: run
          defaultMode: 0744
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend4
  namespace: memphis
  labels:
    app: frontend
    sim-cloud: "Azure"
    sim-region: "us-central-1"
    sim-account: "30"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      sim-cloud: "Azure"
      sim-region: "us-central-1"
      sim-account: "30"
  template:
    metadata:
      labels:
        app: frontend
        sim-cloud: "Azure"
        sim-region: "us-central-1"
        sim-account: "30"
        filter: demo
    spec:
      containers:
      - name: frontend
        image: jodydadescott/stupid-container
        command: ["/scripts/run"]
        ports:
        - containerPort: 80
        env:
        - name: LISTEN
          value: ":80"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_APP
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: wrapper
          mountPath: /scripts
      volumes:
      - name: wrapper
        configMap:
          name: run
          defaultMode: 0744
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend1
  namespace: memphis
  labels:
    app: backend
    sim-cloud: "AWS"
    sim-region: "us-east-1"
    sim-account: "10"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      sim-cloud: "AWS"
      sim-region: "us-east-1"
      sim-account: "10"
  template:
    metadata:
      labels:
        app: backend
        sim-cloud: "AWS"
        sim-region: "us-east-1"
        sim-account: "10"
        filter: demo
    spec:
      containers:
      - name: backend
        image: jodydadescott/stupid-container
        command: ["/scripts/run"]
        ports:
        - containerPort: 80
        env:
        - name: LISTEN
          value: ":80"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_APP
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: wrapper
          mountPath: /scripts
      volumes:
      - name: wrapper
        configMap:
          name: run
          defaultMode: 0744
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend2
  namespace: memphis
  labels:
    app: backend
    sim-cloud: "AWS"
    sim-region: "us-west-1"
    sim-account: "10"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      sim-cloud: "AWS"
      sim-region: "us-west-1"
      sim-account: "10"
  template:
    metadata:
      labels:
        app: backend
        sim-cloud: "AWS"
        sim-region: "us-west-1"
        sim-account: "10"
        filter: demo
    spec:
      containers:
      - name: backend
        image: jodydadescott/stupid-container
        command: ["/scripts/run"]
        ports:
        - containerPort: 80
        env:
        - name: LISTEN
          value: ":80"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_APP
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: wrapper
          mountPath: /scripts
      volumes:
      - name: wrapper
        configMap:
          name: run
          defaultMode: 0744
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend3
  namespace: memphis
  labels:
    app: backend
    sim-cloud: "AWS"
    sim-region: "us-east-1"
    sim-account: "20"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      sim-cloud: "AWS"
      sim-region: "us-east-1"
      sim-account: "20"
  template:
    metadata:
      labels:
        app: backend
        sim-cloud: "AWS"
        sim-region: "us-east-1"
        sim-account: "20"
        filter: demo
    spec:
      containers:
      - name: backend
        image: jodydadescott/stupid-container
        command: ["/scripts/run"]
        ports:
        - containerPort: 80
        env:
        - name: LISTEN
          value: ":80"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_APP
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: wrapper
          mountPath: /scripts
      volumes:
      - name: wrapper
        configMap:
          name: run
          defaultMode: 0744
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend4
  namespace: memphis
  labels:
    app: backend
    sim-cloud: "Azure"
    sim-region: "us-central-1"
    sim-account: "30"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      sim-cloud: "Azure"
      sim-region: "us-central-1"
      sim-account: "30"
  template:
    metadata:
      labels:
        app: backend
        sim-cloud: "Azure"
        sim-region: "us-central-1"
        sim-account: "30"
        filter: demo
    spec:
      containers:
      - name: backend
        image: jodydadescott/stupid-container
        command: ["/scripts/run"]
        ports:
        - containerPort: 80
        env:
        - name: LISTEN
          value: ":80"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_APP
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: wrapper
          mountPath: /scripts
      volumes:
      - name: wrapper
        configMap:
          name: run
          defaultMode: 0744
